version: '3.8'

services:
  nginx:
    depends_on:
      - frontend
      - server
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  frontend:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend

  server:
    image: todo-backend
    environment: 
    - MONGO_URL=mongodb://the_username:the_password@mongo/the_database
    - REDIS_URL=//redis
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongo

  redis:
    image: redis
    ports: 
      - 6379:6379
    volumes:
    - ./todo-backend/redis_data:/data
    container_name: redis

volumes:
  mongo_data:
  